/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tema_8_03.Controlador;

/**
 *
 * @author leora
 */
 
public final class VCliente extends javax.swing.JFrame {
    int posicion;
    String posicionString;
    String palabra;
    String tema;
    public VCliente() {
        initComponents();
    }
     public VCliente(int accion) {
        initComponents();
        switch (accion){
            case 1:
                tema = "Alta";
                enableTodos();
                disableBotones();
                bBuscar.setEnabled(false);
                bBuscar.setVisible(false);
                break;
            case 2:
                tema = "Baja";
                bAceptar.setText("Borrar");
                bAceptar.setEnabled(false);
                break;
            case 3:
                tema = "Modificacion";
                break;
            case 4:
                tema = "Cosulta";
                disableBotones();
                bBuscar.setText("Anterior");
                bAceptar.setText("Siguiente");
                bCancelar.setText("Atrás");
                break;
        }
        lTitulo.setText("Clientes : "+tema);
    }
    public void enableTodos(){
        tfDni.setEnabled(true);
        tfNombre.setEnabled(true);
        tfApellidos.setEnabled(true);
        tfDireccion.setEnabled(true);
        tfTelefono.setEnabled(true);
        tfEmail.setEnabled(true);
    }
    public void disableTodos(){
        tfDni.setEnabled(false);
        tfDni.setText("");
        tfNombre.setEnabled(false);
        tfNombre.setText("");
        tfApellidos.setEnabled(false);
        tfApellidos.setText("");
        tfDireccion.setEnabled(false);
        tfDireccion.setText("");
        tfTelefono.setEnabled(false);
        tfTelefono.setText("");
        tfEmail.setEnabled(false);
        tfEmail.setText("");
    }
    public void enableBotones(){
        bDni.setEnabled(true);
        bNombre.setEnabled(true);
        bApellidos.setEnabled(true);
        bDireccion.setEnabled(true);
        bTelefono.setEnabled(true);
        bEmail.setEnabled(true);
    }
    public void disableBotones(){
        bDni.setEnabled(false);
        bNombre.setEnabled(false);
        bApellidos.setEnabled(false);
        bDireccion.setEnabled(false);
        bTelefono.setEnabled(false);
        bEmail.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        bDni = new javax.swing.JButton();
        bNombre = new javax.swing.JButton();
        bApellidos = new javax.swing.JButton();
        bDireccion = new javax.swing.JButton();
        bTelefono = new javax.swing.JButton();
        bEmail = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("DNI :");

        jLabel2.setText("Nombre :");

        jLabel3.setText("Apellidos :");

        jLabel4.setText("Dirección :");

        jLabel5.setText("Teléfono :");

        jLabel6.setText("E-mail :");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        tfDni.setEnabled(false);
        tfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDniActionPerformed(evt);
            }
        });

        tfNombre.setEnabled(false);

        tfApellidos.setEnabled(false);

        tfDireccion.setEnabled(false);

        tfTelefono.setEnabled(false);

        tfEmail.setEnabled(false);

        bDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDniActionPerformed(evt);
            }
        });

        bNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNombreActionPerformed(evt);
            }
        });

        bApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApellidosActionPerformed(evt);
            }
        });

        bDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDireccionActionPerformed(evt);
            }
        });

        bTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTelefonoActionPerformed(evt);
            }
        });

        bEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmailActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(bBuscar))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(bCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDni)
                            .addComponent(tfNombre)
                            .addComponent(tfApellidos)
                            .addComponent(tfDireccion)
                            .addComponent(tfTelefono)
                            .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bDireccion)
                                .addComponent(bTelefono))
                            .addComponent(bEmail))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bAceptar)
                    .addComponent(bBuscar))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
            String dni = tfDni.getText();
            String nombre = tfNombre.getText();
            String apellidos = tfApellidos.getText();
            String direccion = tfDireccion.getText();
            String telefono = tfTelefono.getText();
            String email = tfEmail.getText();
            try {
                Controlador.datosAlta(dni,nombre,apellidos,direccion,telefono,email);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        Controlador.cancelar();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDniActionPerformed

    private void bDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDniActionPerformed
        buscarPor(1);
        tfDni.requestFocus();
    }//GEN-LAST:event_bDniActionPerformed

    private void bApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApellidosActionPerformed
        buscarPor(3);
        tfApellidos.requestFocus();
    }//GEN-LAST:event_bApellidosActionPerformed

    private void bTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTelefonoActionPerformed
        buscarPor(5);
        tfTelefono.requestFocus();
    }//GEN-LAST:event_bTelefonoActionPerformed

    private void bNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNombreActionPerformed
        buscarPor(2);
        tfNombre.requestFocus();
    }//GEN-LAST:event_bNombreActionPerformed

    private void bDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDireccionActionPerformed
        buscarPor(4);
        tfDireccion.requestFocus();
    }//GEN-LAST:event_bDireccionActionPerformed

    private void bEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmailActionPerformed
        buscarPor(6);
        tfEmail.requestFocus();
    }//GEN-LAST:event_bEmailActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
      
        switch(posicion){
            case 1:
                posicionString= "dni";
                palabra = tfDni.getText();
                break;
            case 2:
                posicionString= "nombre";
                palabra = tfNombre.getText();
                break;
            case 3:
                posicionString= "apellidos";
                palabra = tfApellidos.getText();
                break;
            case 4:
                posicionString= "direccion";
                palabra = tfDireccion.getText();
                break;
            case 5:
                posicionString= "telefono";
                palabra = tfTelefono.getText();
                break;
            case 6:
                posicionString= "email";
                palabra = tfEmail.getText();
                break;               
        }
        try {
            boolean encontrado = Controlador.buscaUno(posicionString,palabra);
            if (encontrado){
                bAceptar.setEnabled(true);
                disableBotones();
            }
            else{
                JOptionPane.showMessageDialog(null,"El cliente solicitado no esta registrado");
                disableTodos();
                enableBotones();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_bBuscarActionPerformed
    public void dameDatos(String dni, String nombre, String apellidos, String direccion, String telefono, String email){
        tfDni.setText(dni);
        tfNombre.setText(nombre);
        tfApellidos.setText(apellidos);
        tfDireccion.setText(direccion);
        tfTelefono.setText(telefono);
        tfEmail.setText(email);
    }
    public void buscarPor(int numero){
        posicion=numero;
        disableTodos();
        enableBotones();
        switch (numero){
            case 1:
                bDni.setEnabled(false);
                tfDni.setEnabled(true);
                
                break;
            case 2:
                bNombre.setEnabled(false);
                tfNombre.setEnabled(true);
                break;
            case 3:
                bApellidos.setEnabled(false);
                tfApellidos.setEnabled(true);
                break;
            case 4:
                bDireccion.setEnabled(false);
                tfDireccion.setEnabled(true);
                break;
            case 5:
                bTelefono.setEnabled(false);
                tfTelefono.setEnabled(true);
                break;
            case 6:
                bEmail.setEnabled(false);
                tfEmail.setEnabled(true);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bApellidos;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bDireccion;
    private javax.swing.JButton bDni;
    private javax.swing.JButton bEmail;
    private javax.swing.JButton bNombre;
    private javax.swing.JButton bTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
