/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import tema_7_01.Controlador;

/**
 *
 * @author blagon
 */
public class V1 extends javax.swing.JFrame {
    private static V2 v2;
    /**
     * Creates new form v1
     */
    public V1() {
    
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        GenerarRandoms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNumero2 = new javax.swing.JTextField();
        tfResultado = new javax.swing.JTextField();
        tfNumero1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfErrores = new javax.swing.JTextField();
        tfIntentos = new javax.swing.JTextField();
        tfAciertos = new javax.swing.JTextField();
        bSalir = new javax.swing.JButton();
        bActivar = new javax.swing.JButton();
        bComprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(430, 280));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setForeground(java.awt.Color.cyan);
        jLabel1.setText("Numero 1");
        jLabel1.setAlignmentX(0.5F);

        jLabel2.setForeground(java.awt.Color.cyan);
        jLabel2.setText("+   Numero 2");
        jLabel2.setAlignmentX(0.5F);

        jLabel3.setForeground(java.awt.Color.cyan);
        jLabel3.setText("=  Resultado");
        jLabel3.setAlignmentX(0.5F);

        tfNumero2.setBackground(new java.awt.Color(0, 0, 0));
        tfNumero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumero2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        tfNumero2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfNumero2.setEnabled(false);
        tfNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero2ActionPerformed(evt);
            }
        });

        tfResultado.setBackground(new java.awt.Color(0, 0, 0));
        tfResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        tfResultado.setEnabled(false);
        tfResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoActionPerformed(evt);
            }
        });

        tfNumero1.setBackground(new java.awt.Color(0, 0, 0));
        tfNumero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumero1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        tfNumero1.setEnabled(false);
        tfNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.cyan);
        jLabel4.setText("Aciertos");

        jLabel5.setForeground(java.awt.Color.cyan);
        jLabel5.setText("Intentos");

        jLabel6.setForeground(java.awt.Color.cyan);
        jLabel6.setText("Errores");

        tfErrores.setBackground(new java.awt.Color(0, 0, 0));
        tfErrores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfErrores.setText("0");
        tfErrores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        tfErrores.setEnabled(false);
        tfErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfErroresActionPerformed(evt);
            }
        });

        tfIntentos.setBackground(new java.awt.Color(0, 0, 0));
        tfIntentos.setForeground(java.awt.Color.magenta);
        tfIntentos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIntentos.setText("0");
        tfIntentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        tfIntentos.setEnabled(false);
        tfIntentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIntentosActionPerformed(evt);
            }
        });

        tfAciertos.setBackground(new java.awt.Color(0, 0, 0));
        tfAciertos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAciertos.setText("0");
        tfAciertos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        tfAciertos.setEnabled(false);
        tfAciertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAciertosActionPerformed(evt);
            }
        });

        bSalir.setBackground(new java.awt.Color(0, 0, 0));
        bSalir.setForeground(java.awt.Color.cyan);
        bSalir.setText("Salir");
        bSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bActivar.setBackground(new java.awt.Color(0, 0, 0));
        bActivar.setForeground(java.awt.Color.cyan);
        bActivar.setText("Activar");
        bActivar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        bActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActivarActionPerformed(evt);
            }
        });

        bComprobar.setBackground(new java.awt.Color(0, 0, 0));
        bComprobar.setForeground(java.awt.Color.cyan);
        bComprobar.setText("Comprobar");
        bComprobar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.magenta, java.awt.Color.magenta));
        bComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNumero1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(tfIntentos))
                        .addGap(18, 18, 18))
                    .addComponent(bActivar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(bComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(tfErrores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bComprobar)
                    .addComponent(bSalir)
                    .addComponent(bActivar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumero2ActionPerformed

    private void tfResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultadoActionPerformed

    private void tfNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumero1ActionPerformed

    private void tfErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfErroresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfErroresActionPerformed

    private void tfIntentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIntentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIntentosActionPerformed

    private void tfAciertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAciertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAciertosActionPerformed

    private void bActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActivarActionPerformed
        GenerarRandoms();
       
    }//GEN-LAST:event_bActivarActionPerformed
    private void GenerarRandoms(){
     int numero1 =(int)(Math.random()*1000);
        tfNumero1.setText(""+numero1);
        int numero2 =(int)(Math.random()*1000);
        tfNumero2.setText(""+numero2);
    }
    private void bComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprobarActionPerformed
        try{
        int respuestaUsuario= Integer.parseInt(JOptionPane.showInputDialog("Cuanto es  "+tfNumero1.getText()+"  +  "+tfNumero2.getText()+" ?"));
        if (respuestaUsuario == (Integer.parseInt(tfNumero1.getText())+Integer.parseInt(tfNumero2.getText()))){
            tfIntentos.setText(""+(Integer.parseInt(tfIntentos.getText())+1));
            tfAciertos.setText(""+(Integer.parseInt(tfAciertos.getText())+1));
            GenerarRandoms();
        }
        
        if((Integer.parseInt(tfAciertos.getText()))==(Integer.parseInt(tfErrores.getText())+5)){
            v2= new V2();
            v2.setVisible(true); 
            bSalir.doClick();
        }
        }
        catch (Exception e){
            e.getClass();
            tfIntentos.setText(""+(Integer.parseInt(tfIntentos.getText())+1));
            tfErrores.setText(""+(Integer.parseInt(tfErrores.getText())+1));
        }
    }//GEN-LAST:event_bComprobarActionPerformed
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        Controlador.salir();
    }//GEN-LAST:event_bSalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V1().setVisible(true);
            }
        });
    }
    public static void salir(){
        v2.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActivar;
    private javax.swing.JButton bComprobar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfAciertos;
    private javax.swing.JTextField tfErrores;
    private javax.swing.JTextField tfIntentos;
    private javax.swing.JTextField tfNumero1;
    private javax.swing.JTextField tfNumero2;
    private javax.swing.JTextField tfResultado;
    // End of variables declaration//GEN-END:variables
}
