/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author leora
 */
public class vInicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public String usuarioFalso="falso";
    public vInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuario = new javax.swing.JTextField();
        lUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bNoCuenta = new javax.swing.JButton();
        bOlvidadoContrasena = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bAcceder = new javax.swing.JButton();
        tfContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lUsuario.setText("Nombre de usuario");

        jLabel2.setText("Contraseña");

        bNoCuenta.setText("No tengo cuenta");
        bNoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoCuentaActionPerformed(evt);
            }
        });

        bOlvidadoContrasena.setText("He olvidado mi contrasena");
        bOlvidadoContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOlvidadoContrasenaActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bAcceder.setText("Acceder");
        bAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bOlvidadoContrasena))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bAcceder)
                                        .addGap(89, 89, 89)
                                        .addComponent(bNoCuenta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lUsuario)
                                            .addComponent(jLabel2))
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(tfContrasena)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(bSalir)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bNoCuenta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(bAcceder)))
                .addGap(18, 18, 18)
                .addComponent(bOlvidadoContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        vInicioControlador.salir();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccederActionPerformed
        if (!tfUsuario.getText().equals(usuarioFalso)){
        String usuario = tfUsuario.getText();
        char[] contrasena = tfContrasena.getPassword();
        String contrasenaString= String.valueOf(contrasena);
        try {
            vInicioControlador.acceder(usuario,contrasenaString);
            
        } catch (SQLException ex) {
            Logger.getLogger(vInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            vInicioControlador.usuarioFalso();
        }
    }//GEN-LAST:event_bAccederActionPerformed

    private void bNoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoCuentaActionPerformed
        vInicioControlador.noCuenta();
    }//GEN-LAST:event_bNoCuentaActionPerformed

    private void bOlvidadoContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOlvidadoContrasenaActionPerformed
        vInicioControlador.olvidadoContrasena();
    }//GEN-LAST:event_bOlvidadoContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vInicio().setVisible(true);
            }
        });
    }
    public void bloquearVentana(){
        bAcceder.setEnabled(false);
        bNoCuenta.setEnabled(false);
        bOlvidadoContrasena.setEnabled(false);
        bSalir.setEnabled(false);
        tfUsuario.setEnabled(false);
        tfContrasena.setEnabled(false);
    }
    public void desbloquearVentana(){
        bAcceder.setEnabled(true);
        bNoCuenta.setEnabled(true);
        bOlvidadoContrasena.setEnabled(true);
        bSalir.setEnabled(true);
        tfUsuario.setEnabled(true);
        tfContrasena.setEnabled(true);
    }
    public void mensajeV1(String usuario){
        tfUsuario.setText(usuario);
        tfContrasena.setText("");
    }
    public void limpiar(){
        usuarioFalso = tfUsuario.getText();
        tfUsuario.setText("");
        tfContrasena.setText("");
    }
    public void limpiarContrasena(){
        tfContrasena.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcceder;
    private javax.swing.JButton bNoCuenta;
    private javax.swing.JButton bOlvidadoContrasena;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JPasswordField tfContrasena;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
